export const ROUTES = {
  LOGIN: '/login',
  ADMIN_ROOT: '/admin',
  DASHBOARD: '/admin/dashboard',
  USERS: '/admin/users',
  MERCHANTS: '/admin/merchants',
  KYC: '/admin/kyc',
  WALLETS: '/admin/wallets',
  PAYMENT_ORDERS: '/admin/payment-orders',
  TRANSACTIONS: '/admin/transactions',
  TOPUPS: '/admin/topups',
  TRANSFERS: '/admin/transfers',
  REFUNDS: '/admin/refunds',
  QR_PAYMENTS: '/admin/qr-payments',
  REPORTS: '/admin/reports',
  WEBHOOKS: '/admin/webhooks',
  LOGS: '/admin/logs',
  ROLES: '/admin/roles',
  STAFFS: '/admin/staffs',
  SETTINGS: '/admin/settings',
};
