-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.app_settings
(
    id uuid NOT NULL,
    setting_group character varying(100) COLLATE pg_catalog."default" NOT NULL,
    setting_key character varying(150) COLLATE pg_catalog."default" NOT NULL,
    setting_value jsonb NOT NULL,
    value_type character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'STRING'::character varying,
    description text COLLATE pg_catalog."default",
    is_sensitive boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT app_settings_pkey PRIMARY KEY (id),
    CONSTRAINT app_settings_setting_key_key UNIQUE (setting_key)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    trace_id character varying(100) COLLATE pg_catalog."default",
    actor_type character varying(50) COLLATE pg_catalog."default",
    actor_id uuid,
    action character varying(100) COLLATE pg_catalog."default" NOT NULL,
    entity_type character varying(100) COLLATE pg_catalog."default",
    entity_id uuid,
    old_data jsonb,
    new_data jsonb,
    metadata jsonb,
    reason text COLLATE pg_catalog."default",
    ip_address character varying(50) COLLATE pg_catalog."default",
    user_agent character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chat_messages
(
    id uuid NOT NULL,
    sender_wallet_id uuid NOT NULL,
    receiver_wallet_id uuid NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    message_type character varying(20) COLLATE pg_catalog."default" DEFAULT 'TEXT'::character varying,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'SENT'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT chat_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.code_sequences
(
    id uuid NOT NULL,
    resource_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    prefix character varying(20) COLLATE pg_catalog."default" NOT NULL,
    current_value bigint NOT NULL DEFAULT 0,
    padding integer NOT NULL DEFAULT 6,
    reset_policy character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'NONE'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT code_sequences_pkey PRIMARY KEY (id),
    CONSTRAINT code_sequences_resource_name_key UNIQUE (resource_name)
);

CREATE TABLE IF NOT EXISTS public.deposit_transactions
(
    id uuid NOT NULL,
    deposit_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    user_id uuid NOT NULL,
    wallet_id uuid NOT NULL,
    amount bigint NOT NULL,
    currency character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'VND'::character varying,
    deposit_method character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'SANDBOX_BANK'::character varying,
    external_reference character varying(255) COLLATE pg_catalog."default",
    idempotency_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    failure_reason text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT deposit_transactions_pkey PRIMARY KEY (id),
    CONSTRAINT deposit_transactions_deposit_no_key UNIQUE (deposit_no)
);

CREATE TABLE IF NOT EXISTS public.group_funding_members
(
    id uuid NOT NULL,
    group_funding_id uuid NOT NULL,
    user_id uuid,
    wallet_id uuid,
    amount bigint NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    paid_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT group_funding_members_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.group_fundings
(
    id uuid NOT NULL,
    creator_user_id uuid,
    creator_wallet_id uuid,
    type group_funding_type NOT NULL,
    total_amount bigint NOT NULL,
    remaining_amount bigint NOT NULL,
    total_count integer NOT NULL,
    remaining_count integer NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVE'::character varying,
    message text COLLATE pg_catalog."default",
    expires_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT group_fundings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.idempotency_keys
(
    id uuid NOT NULL,
    actor_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    actor_id uuid NOT NULL,
    idempotency_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    request_path character varying(255) COLLATE pg_catalog."default" NOT NULL,
    request_hash text COLLATE pg_catalog."default" NOT NULL,
    resource_type character varying(100) COLLATE pg_catalog."default",
    resource_id uuid,
    response_status_code integer,
    response_body jsonb,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PROCESSING'::character varying,
    locked_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT idempotency_keys_pkey PRIMARY KEY (id),
    CONSTRAINT idempotency_keys_actor_key_unique UNIQUE (actor_type, actor_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.ledger_entries
(
    id uuid NOT NULL,
    ledger_transaction_id uuid NOT NULL,
    account_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    wallet_id uuid,
    merchant_id uuid,
    system_account_code character varying(50) COLLATE pg_catalog."default",
    entry_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    amount bigint NOT NULL,
    balance_before bigint NOT NULL,
    balance_after bigint NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ledger_entries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ledger_transactions
(
    id uuid NOT NULL,
    transaction_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    transaction_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    amount bigint NOT NULL,
    currency character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'VND'::character varying,
    source_type character varying(50) COLLATE pg_catalog."default",
    source_id uuid,
    idempotency_key character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    created_by uuid,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ledger_transactions_pkey PRIMARY KEY (id),
    CONSTRAINT ledger_transactions_transaction_no_key UNIQUE (transaction_no)
);

CREATE TABLE IF NOT EXISTS public.merchant_api_keys
(
    id uuid NOT NULL,
    merchant_id uuid NOT NULL,
    key_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    api_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    api_secret_hash text COLLATE pg_catalog."default" NOT NULL,
    environment character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'SANDBOX'::character varying,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVE'::character varying,
    last_used_at timestamp with time zone,
    expired_at timestamp with time zone,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT merchant_api_keys_pkey PRIMARY KEY (id),
    CONSTRAINT merchant_api_keys_api_key_key UNIQUE (api_key)
);

CREATE TABLE IF NOT EXISTS public.merchant_balances
(
    merchant_id uuid NOT NULL,
    available_balance bigint NOT NULL DEFAULT 0,
    pending_balance bigint NOT NULL DEFAULT 0,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT merchant_balances_pkey PRIMARY KEY (merchant_id)
);

CREATE TABLE IF NOT EXISTS public.merchant_callback_configs
(
    id uuid NOT NULL,
    merchant_id uuid NOT NULL,
    default_callback_url text COLLATE pg_catalog."default" NOT NULL,
    default_redirect_url text COLLATE pg_catalog."default",
    webhook_secret_hash text COLLATE pg_catalog."default" NOT NULL,
    callback_enabled boolean NOT NULL DEFAULT true,
    retry_enabled boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT merchant_callback_configs_pkey PRIMARY KEY (id),
    CONSTRAINT merchant_callback_configs_merchant_unique UNIQUE (merchant_id)
);

CREATE TABLE IF NOT EXISTS public.merchant_users
(
    id uuid NOT NULL,
    merchant_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role_code character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT 'MERCHANT_STAFF'::character varying,
    is_owner boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT merchant_users_pkey PRIMARY KEY (id),
    CONSTRAINT merchant_users_merchant_user_unique UNIQUE (merchant_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.merchants
(
    id uuid NOT NULL,
    merchant_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    merchant_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    business_type character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ONLINE'::character varying,
    representative_name character varying(255) COLLATE pg_catalog."default",
    tax_code character varying(50) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING_REVIEW'::character varying,
    risk_note text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT merchants_pkey PRIMARY KEY (id),
    CONSTRAINT merchants_email_unique UNIQUE (email),
    CONSTRAINT merchants_merchant_code_key UNIQUE (merchant_code)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    notification_type character varying(50) COLLATE pg_catalog."default",
    reference_id uuid,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'UNREAD'::character varying,
    read_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.otp_tracking
(
    id uuid NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    otp_hash text COLLATE pg_catalog."default" NOT NULL,
    purpose character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'AUTH'::character varying,
    failed_attempts integer NOT NULL DEFAULT 0,
    locked_until timestamp with time zone,
    expired_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT otp_tracking_pkey PRIMARY KEY (id),
    CONSTRAINT otp_tracking_phone_key UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS public.outbox_events
(
    id uuid NOT NULL,
    aggregate_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    aggregate_id uuid NOT NULL,
    event_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    payload jsonb NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT outbox_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.password_resets
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    reset_token_hash text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT password_resets_pkey PRIMARY KEY (id),
    CONSTRAINT password_resets_reset_token_hash_key UNIQUE (reset_token_hash)
);

CREATE TABLE IF NOT EXISTS public.payment_orders
(
    id uuid NOT NULL,
    merchant_id uuid NOT NULL,
    payment_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    merchant_order_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    amount bigint NOT NULL,
    currency character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'VND'::character varying,
    callback_url text COLLATE pg_catalog."default" NOT NULL,
    redirect_url text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    refund_status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'NONE'::character varying,
    refunded_amount bigint NOT NULL DEFAULT 0,
    idempotency_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    metadata jsonb,
    expired_at timestamp with time zone NOT NULL,
    paid_at timestamp with time zone,
    canceled_at timestamp with time zone,
    failed_reason text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT payment_orders_pkey PRIMARY KEY (id),
    CONSTRAINT payment_orders_merchant_idempotency_unique UNIQUE (merchant_id, idempotency_key),
    CONSTRAINT payment_orders_merchant_order_unique UNIQUE (merchant_id, merchant_order_id),
    CONSTRAINT payment_orders_payment_no_key UNIQUE (payment_no)
);

CREATE TABLE IF NOT EXISTS public.payment_qr_codes
(
    id uuid NOT NULL,
    payment_order_id uuid NOT NULL,
    qr_token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    qr_payload text COLLATE pg_catalog."default" NOT NULL,
    qr_image_url text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVE'::character varying,
    expired_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT payment_qr_codes_pkey PRIMARY KEY (id),
    CONSTRAINT payment_qr_codes_qr_token_key UNIQUE (qr_token)
);

CREATE TABLE IF NOT EXISTS public.payment_transactions
(
    id uuid NOT NULL,
    payment_order_id uuid NOT NULL,
    payer_user_id uuid NOT NULL,
    payer_wallet_id uuid NOT NULL,
    amount bigint NOT NULL,
    currency character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'VND'::character varying,
    idempotency_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    failure_reason text COLLATE pg_catalog."default",
    paid_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
    CONSTRAINT payment_transactions_payer_idempotency_unique UNIQUE (payer_user_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.permissions
(
    id uuid NOT NULL,
    code character varying(150) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT permissions_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    token_family_id uuid NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    reused_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by_ip character varying(45) COLLATE pg_catalog."default",
    revoked_by_ip character varying(45) COLLATE pg_catalog."default",
    user_agent character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS public.refund_transactions
(
    id uuid NOT NULL,
    refund_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    payment_order_id uuid NOT NULL,
    payment_transaction_id uuid,
    merchant_id uuid NOT NULL,
    user_id uuid NOT NULL,
    wallet_id uuid NOT NULL,
    amount bigint NOT NULL,
    currency character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'VND'::character varying,
    description character varying(500) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    idempotency_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    failure_reason text COLLATE pg_catalog."default",
    created_by uuid,
    refunded_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT refund_transactions_pkey PRIMARY KEY (id),
    CONSTRAINT refund_transactions_refund_no_key UNIQUE (refund_no)
);

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id uuid NOT NULL,
    code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    scope character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'SYSTEM'::character varying,
    description text COLLATE pg_catalog."default",
    is_system boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.user_devices
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    fcm_token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    device_name character varying(100) COLLATE pg_catalog."default",
    device_type character varying(20) COLLATE pg_catalog."default",
    last_seen_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_devices_pkey PRIMARY KEY (id),
    CONSTRAINT user_devices_fcm_token_key UNIQUE (fcm_token)
);

CREATE TABLE IF NOT EXISTS public.user_kyc
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    id_number character varying(20) COLLATE pg_catalog."default",
    full_name character varying(255) COLLATE pg_catalog."default",
    dob character varying(20) COLLATE pg_catalog."default",
    gender character varying(10) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    id_front_image text COLLATE pg_catalog."default" NOT NULL,
    id_back_image text COLLATE pg_catalog."default" NOT NULL,
    face_image text COLLATE pg_catalog."default" NOT NULL,
    kyc_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    face_match_score numeric,
    rejection_reason text COLLATE pg_catalog."default",
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_kyc_pkey PRIMARY KEY (id),
    CONSTRAINT user_kyc_id_number_key UNIQUE (id_number),
    CONSTRAINT user_kyc_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    user_type character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'USER'::character varying,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(100) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVE'::character varying,
    failed_login_attempts integer NOT NULL DEFAULT 0,
    locked_until timestamp with time zone,
    last_login_at timestamp with time zone,
    is_kyc_verified boolean NOT NULL DEFAULT false,
    pin_hash text COLLATE pg_catalog."default",
    token_version integer NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    loyalty_member_id character varying(255) COLLATE pg_catalog."default",
    email_otp character varying(10) COLLATE pg_catalog."default",
    email_otp_expired_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_phone_unique UNIQUE (phone),
    CONSTRAINT users_username_unique UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.wallet_balances
(
    wallet_id uuid NOT NULL,
    available_balance bigint NOT NULL DEFAULT 0,
    locked_balance bigint NOT NULL DEFAULT 0,
    loyalty_points bigint NOT NULL DEFAULT 0,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT wallet_balances_pkey PRIMARY KEY (wallet_id)
);

CREATE TABLE IF NOT EXISTS public.wallet_limits
(
    wallet_id uuid NOT NULL,
    daily_deposit_limit bigint DEFAULT 50000000,
    daily_withdrawal_limit bigint DEFAULT 50000000,
    daily_transaction_limit bigint DEFAULT 50000000,
    monthly_transaction_limit bigint DEFAULT 100000000,
    monthly_special_service_limit bigint DEFAULT 300000000,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT wallet_limits_pkey PRIMARY KEY (wallet_id)
);

CREATE TABLE IF NOT EXISTS public.wallet_linked_banks
(
    id uuid NOT NULL,
    wallet_id uuid NOT NULL,
    bank_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    bank_code character varying(20) COLLATE pg_catalog."default",
    card_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    card_holder_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    issue_date character varying(10) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVE'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT wallet_linked_banks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.wallet_transfers
(
    id uuid NOT NULL,
    transfer_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    sender_user_id uuid NOT NULL,
    sender_wallet_id uuid NOT NULL,
    receiver_user_id uuid NOT NULL,
    receiver_wallet_id uuid NOT NULL,
    amount bigint NOT NULL,
    currency character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'VND'::character varying,
    description character varying(255) COLLATE pg_catalog."default",
    idempotency_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    failure_reason text COLLATE pg_catalog."default",
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT wallet_transfers_pkey PRIMARY KEY (id),
    CONSTRAINT wallet_transfers_transfer_no_key UNIQUE (transfer_no)
);

CREATE TABLE IF NOT EXISTS public.wallets
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    wallet_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    wallet_code character varying(50) COLLATE pg_catalog."default",
    wallet_type character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PERSONAL'::character varying,
    currency character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'VND'::character varying,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVE'::character varying,
    lock_reason text COLLATE pg_catalog."default",
    locked_at timestamp with time zone,
    locked_by uuid,
    closed_at timestamp with time zone,
    pin_failed_attempts integer NOT NULL DEFAULT 0,
    pin_locked_until timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT wallets_pkey PRIMARY KEY (id),
    CONSTRAINT wallets_user_id_unique UNIQUE (user_id),
    CONSTRAINT wallets_wallet_code_unique UNIQUE (wallet_code),
    CONSTRAINT wallets_wallet_no_key UNIQUE (wallet_no)
);

CREATE TABLE IF NOT EXISTS public.withdrawal_transactions
(
    id uuid NOT NULL,
    withdrawal_no character varying(50) COLLATE pg_catalog."default",
    user_id uuid NOT NULL,
    wallet_id uuid NOT NULL,
    linked_bank_id uuid,
    amount bigint NOT NULL,
    currency character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'VND'::character varying,
    withdrawal_method character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'SANDBOX_BANK'::character varying,
    external_reference character varying(255) COLLATE pg_catalog."default",
    idempotency_key character varying(255) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    failure_reason text COLLATE pg_catalog."default",
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT withdrawal_transactions_pkey PRIMARY KEY (id),
    CONSTRAINT withdrawal_transactions_withdrawal_no_key UNIQUE (withdrawal_no)
);

ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT chat_messages_receiver_wallet_id_fkey FOREIGN KEY (receiver_wallet_id)
    REFERENCES public.wallets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT chat_messages_sender_wallet_id_fkey FOREIGN KEY (sender_wallet_id)
    REFERENCES public.wallets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.deposit_transactions
    ADD CONSTRAINT deposit_transactions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.deposit_transactions
    ADD CONSTRAINT deposit_transactions_wallet_id_fkey FOREIGN KEY (wallet_id)
    REFERENCES public.wallets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.group_funding_members
    ADD CONSTRAINT group_funding_members_group_funding_id_fkey FOREIGN KEY (group_funding_id)
    REFERENCES public.group_fundings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ledger_entries
    ADD CONSTRAINT ledger_entries_ledger_transaction_id_fkey FOREIGN KEY (ledger_transaction_id)
    REFERENCES public.ledger_transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ledger_entries
    ADD CONSTRAINT ledger_entries_merchant_id_fkey FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ledger_entries
    ADD CONSTRAINT ledger_entries_wallet_id_fkey FOREIGN KEY (wallet_id)
    REFERENCES public.wallets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ledger_transactions
    ADD CONSTRAINT ledger_transactions_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.merchant_api_keys
    ADD CONSTRAINT merchant_api_keys_merchant_id_fkey FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.merchant_balances
    ADD CONSTRAINT merchant_balances_merchant_id_fkey FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS merchant_balances_pkey
    ON public.merchant_balances(merchant_id);


ALTER TABLE IF EXISTS public.merchant_callback_configs
    ADD CONSTRAINT merchant_callback_configs_merchant_id_fkey FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS merchant_callback_configs_merchant_unique
    ON public.merchant_callback_configs(merchant_id);


ALTER TABLE IF EXISTS public.merchant_users
    ADD CONSTRAINT merchant_users_merchant_id_fkey FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.merchant_users
    ADD CONSTRAINT merchant_users_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.password_resets
    ADD CONSTRAINT password_resets_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment_orders
    ADD CONSTRAINT payment_orders_merchant_id_fkey FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment_qr_codes
    ADD CONSTRAINT payment_qr_codes_payment_order_id_fkey FOREIGN KEY (payment_order_id)
    REFERENCES public.payment_orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment_transactions
    ADD CONSTRAINT payment_transactions_payer_user_id_fkey FOREIGN KEY (payer_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment_transactions
    ADD CONSTRAINT payment_transactions_payer_wallet_id_fkey FOREIGN KEY (payer_wallet_id)
    REFERENCES public.wallets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment_transactions
    ADD CONSTRAINT payment_transactions_payment_order_id_fkey FOREIGN KEY (payment_order_id)
    REFERENCES public.payment_orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.refund_transactions
    ADD CONSTRAINT refund_transactions_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.refund_transactions
    ADD CONSTRAINT refund_transactions_merchant_id_fkey FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.refund_transactions
    ADD CONSTRAINT refund_transactions_payment_order_id_fkey FOREIGN KEY (payment_order_id)
    REFERENCES public.payment_orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.refund_transactions
    ADD CONSTRAINT refund_transactions_payment_transaction_id_fkey FOREIGN KEY (payment_transaction_id)
    REFERENCES public.payment_transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.refund_transactions
    ADD CONSTRAINT refund_transactions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.refund_transactions
    ADD CONSTRAINT refund_transactions_wallet_id_fkey FOREIGN KEY (wallet_id)
    REFERENCES public.wallets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_devices
    ADD CONSTRAINT user_devices_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_kyc
    ADD CONSTRAINT user_kyc_reviewed_by_fkey FOREIGN KEY (reviewed_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_kyc
    ADD CONSTRAINT user_kyc_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS user_kyc_user_id_key
    ON public.user_kyc(user_id);


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallet_balances
    ADD CONSTRAINT wallet_balances_wallet_id_fkey FOREIGN KEY (wallet_id)
    REFERENCES public.wallets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS wallet_balances_pkey
    ON public.wallet_balances(wallet_id);


ALTER TABLE IF EXISTS public.wallet_limits
    ADD CONSTRAINT wallet_limits_wallet_id_fkey FOREIGN KEY (wallet_id)
    REFERENCES public.wallets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS wallet_limits_pkey
    ON public.wallet_limits(wallet_id);


ALTER TABLE IF EXISTS public.wallet_linked_banks
    ADD CONSTRAINT wallet_linked_banks_wallet_id_fkey FOREIGN KEY (wallet_id)
    REFERENCES public.wallets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.wallet_transfers
    ADD CONSTRAINT wallet_transfers_receiver_user_id_fkey FOREIGN KEY (receiver_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallet_transfers
    ADD CONSTRAINT wallet_transfers_receiver_wallet_id_fkey FOREIGN KEY (receiver_wallet_id)
    REFERENCES public.wallets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallet_transfers
    ADD CONSTRAINT wallet_transfers_sender_user_id_fkey FOREIGN KEY (sender_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallet_transfers
    ADD CONSTRAINT wallet_transfers_sender_wallet_id_fkey FOREIGN KEY (sender_wallet_id)
    REFERENCES public.wallets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallets
    ADD CONSTRAINT wallets_locked_by_fkey FOREIGN KEY (locked_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallets
    ADD CONSTRAINT wallets_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS wallets_user_id_unique
    ON public.wallets(user_id);


ALTER TABLE IF EXISTS public.withdrawal_transactions
    ADD CONSTRAINT withdrawal_transactions_linked_bank_id_fkey FOREIGN KEY (linked_bank_id)
    REFERENCES public.wallet_linked_banks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.withdrawal_transactions
    ADD CONSTRAINT withdrawal_transactions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.withdrawal_transactions
    ADD CONSTRAINT withdrawal_transactions_wallet_id_fkey FOREIGN KEY (wallet_id)
    REFERENCES public.wallets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;